/**
 * This class is generated by jOOQ
 */
package com.infsystem.infsystem.databse.jooq.model.tables;


import com.infsystem.infsystem.databse.jooq.model.Inf;
import com.infsystem.infsystem.databse.jooq.model.Keys;
import com.infsystem.infsystem.databse.jooq.model.tables.records.BookMediumRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BookMedium extends TableImpl<BookMediumRecord> {

    private static final long serialVersionUID = 348450849;

    /**
     * The reference instance of <code>inf.book_medium</code>
     */
    public static final BookMedium BOOK_MEDIUM = new BookMedium();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BookMediumRecord> getRecordType() {
        return BookMediumRecord.class;
    }

    /**
     * The column <code>inf.book_medium.id</code>.
     */
    public final TableField<BookMediumRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>inf.book_medium.medium</code>.
     */
    public final TableField<BookMediumRecord, String> MEDIUM = createField("medium", org.jooq.impl.SQLDataType.VARCHAR.length(60), this, "");

    /**
     * Create a <code>inf.book_medium</code> table reference
     */
    public BookMedium() {
        this("book_medium", null);
    }

    /**
     * Create an aliased <code>inf.book_medium</code> table reference
     */
    public BookMedium(String alias) {
        this(alias, BOOK_MEDIUM);
    }

    private BookMedium(String alias, Table<BookMediumRecord> aliased) {
        this(alias, aliased, null);
    }

    private BookMedium(String alias, Table<BookMediumRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Inf.INF;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<BookMediumRecord, Integer> getIdentity() {
        return Keys.IDENTITY_BOOK_MEDIUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<BookMediumRecord> getPrimaryKey() {
        return Keys.KEY_BOOK_MEDIUM_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<BookMediumRecord>> getKeys() {
        return Arrays.<UniqueKey<BookMediumRecord>>asList(Keys.KEY_BOOK_MEDIUM_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookMedium as(String alias) {
        return new BookMedium(alias, this);
    }

    /**
     * Rename this table
     */
    public BookMedium rename(String name) {
        return new BookMedium(name, null);
    }
}
