/**
 * This class is generated by jOOQ
 */
package com.infsystem.infsystem.databse.jooq.model.tables;


import com.infsystem.infsystem.databse.jooq.model.Inf;
import com.infsystem.infsystem.databse.jooq.model.Keys;
import com.infsystem.infsystem.databse.jooq.model.tables.records.MaterialCategoryRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MaterialCategory extends TableImpl<MaterialCategoryRecord> {

    private static final long serialVersionUID = -1402292213;

    /**
     * The reference instance of <code>inf.material_category</code>
     */
    public static final MaterialCategory MATERIAL_CATEGORY = new MaterialCategory();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MaterialCategoryRecord> getRecordType() {
        return MaterialCategoryRecord.class;
    }

    /**
     * The column <code>inf.material_category.id</code>.
     */
    public final TableField<MaterialCategoryRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>inf.material_category.name</code>.
     */
    public final TableField<MaterialCategoryRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(60), this, "");

    /**
     * Create a <code>inf.material_category</code> table reference
     */
    public MaterialCategory() {
        this("material_category", null);
    }

    /**
     * Create an aliased <code>inf.material_category</code> table reference
     */
    public MaterialCategory(String alias) {
        this(alias, MATERIAL_CATEGORY);
    }

    private MaterialCategory(String alias, Table<MaterialCategoryRecord> aliased) {
        this(alias, aliased, null);
    }

    private MaterialCategory(String alias, Table<MaterialCategoryRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Inf.INF;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<MaterialCategoryRecord, Integer> getIdentity() {
        return Keys.IDENTITY_MATERIAL_CATEGORY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<MaterialCategoryRecord> getPrimaryKey() {
        return Keys.KEY_MATERIAL_CATEGORY_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<MaterialCategoryRecord>> getKeys() {
        return Arrays.<UniqueKey<MaterialCategoryRecord>>asList(Keys.KEY_MATERIAL_CATEGORY_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MaterialCategory as(String alias) {
        return new MaterialCategory(alias, this);
    }

    /**
     * Rename this table
     */
    public MaterialCategory rename(String name) {
        return new MaterialCategory(name, null);
    }
}
