/**
 * This class is generated by jOOQ
 */
package com.infsystem.infsystem.databse.jooq.model.tables;


import com.infsystem.infsystem.databse.jooq.model.Inf;
import com.infsystem.infsystem.databse.jooq.model.Keys;
import com.infsystem.infsystem.databse.jooq.model.tables.records.StateRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class State extends TableImpl<StateRecord> {

    private static final long serialVersionUID = 41737517;

    /**
     * The reference instance of <code>inf.state</code>
     */
    public static final State STATE = new State();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<StateRecord> getRecordType() {
        return StateRecord.class;
    }

    /**
     * The column <code>inf.state.id</code>.
     */
    public final TableField<StateRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>inf.state.name</code>.
     */
    public final TableField<StateRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(30), this, "");

    /**
     * Create a <code>inf.state</code> table reference
     */
    public State() {
        this("state", null);
    }

    /**
     * Create an aliased <code>inf.state</code> table reference
     */
    public State(String alias) {
        this(alias, STATE);
    }

    private State(String alias, Table<StateRecord> aliased) {
        this(alias, aliased, null);
    }

    private State(String alias, Table<StateRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Inf.INF;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<StateRecord, Integer> getIdentity() {
        return Keys.IDENTITY_STATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<StateRecord> getPrimaryKey() {
        return Keys.KEY_STATE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<StateRecord>> getKeys() {
        return Arrays.<UniqueKey<StateRecord>>asList(Keys.KEY_STATE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public State as(String alias) {
        return new State(alias, this);
    }

    /**
     * Rename this table
     */
    public State rename(String name) {
        return new State(name, null);
    }
}
