/**
 * This class is generated by jOOQ
 */
package com.infsystem.infsystem.databse.jooq.model.tables;


import com.infsystem.infsystem.databse.jooq.model.Inf;
import com.infsystem.infsystem.databse.jooq.model.Keys;
import com.infsystem.infsystem.databse.jooq.model.tables.records.TaskStateRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TaskState extends TableImpl<TaskStateRecord> {

    private static final long serialVersionUID = -750937848;

    /**
     * The reference instance of <code>inf.task_state</code>
     */
    public static final TaskState TASK_STATE = new TaskState();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TaskStateRecord> getRecordType() {
        return TaskStateRecord.class;
    }

    /**
     * The column <code>inf.task_state.id</code>.
     */
    public final TableField<TaskStateRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>inf.task_state.name</code>.
     */
    public final TableField<TaskStateRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(30), this, "");

    /**
     * Create a <code>inf.task_state</code> table reference
     */
    public TaskState() {
        this("task_state", null);
    }

    /**
     * Create an aliased <code>inf.task_state</code> table reference
     */
    public TaskState(String alias) {
        this(alias, TASK_STATE);
    }

    private TaskState(String alias, Table<TaskStateRecord> aliased) {
        this(alias, aliased, null);
    }

    private TaskState(String alias, Table<TaskStateRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Inf.INF;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TaskStateRecord, Integer> getIdentity() {
        return Keys.IDENTITY_TASK_STATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TaskStateRecord> getPrimaryKey() {
        return Keys.KEY_TASK_STATE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TaskStateRecord>> getKeys() {
        return Arrays.<UniqueKey<TaskStateRecord>>asList(Keys.KEY_TASK_STATE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TaskState as(String alias) {
        return new TaskState(alias, this);
    }

    /**
     * Rename this table
     */
    public TaskState rename(String name) {
        return new TaskState(name, null);
    }
}
