/**
 * This class is generated by jOOQ
 */
package com.infsystem.infsystem.databse.jooq.model.tables;


import com.infsystem.infsystem.databse.jooq.model.Inf;
import com.infsystem.infsystem.databse.jooq.model.Keys;
import com.infsystem.infsystem.databse.jooq.model.tables.records.TeliphoneRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Teliphone extends TableImpl<TeliphoneRecord> {

    private static final long serialVersionUID = -1896415014;

    /**
     * The reference instance of <code>inf.teliphone</code>
     */
    public static final Teliphone TELIPHONE = new Teliphone();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TeliphoneRecord> getRecordType() {
        return TeliphoneRecord.class;
    }

    /**
     * The column <code>inf.teliphone.id</code>.
     */
    public final TableField<TeliphoneRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>inf.teliphone.number</code>.
     */
    public final TableField<TeliphoneRecord, String> NUMBER = createField("number", org.jooq.impl.SQLDataType.CHAR.length(13).nullable(false), this, "");

    /**
     * Create a <code>inf.teliphone</code> table reference
     */
    public Teliphone() {
        this("teliphone", null);
    }

    /**
     * Create an aliased <code>inf.teliphone</code> table reference
     */
    public Teliphone(String alias) {
        this(alias, TELIPHONE);
    }

    private Teliphone(String alias, Table<TeliphoneRecord> aliased) {
        this(alias, aliased, null);
    }

    private Teliphone(String alias, Table<TeliphoneRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Inf.INF;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TeliphoneRecord> getPrimaryKey() {
        return Keys.KEY_TELIPHONE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TeliphoneRecord>> getKeys() {
        return Arrays.<UniqueKey<TeliphoneRecord>>asList(Keys.KEY_TELIPHONE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<TeliphoneRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<TeliphoneRecord, ?>>asList(Keys.FK_TELIPHONE_PERSON);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Teliphone as(String alias) {
        return new Teliphone(alias, this);
    }

    /**
     * Rename this table
     */
    public Teliphone rename(String name) {
        return new Teliphone(name, null);
    }
}
