/**
 * This class is generated by jOOQ
 */
package com.infsystem.infsystem.databse.jooq.model.tables.records;


import com.infsystem.infsystem.databse.jooq.model.tables.Book;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BookRecord extends UpdatableRecordImpl<BookRecord> implements Record10<Integer, Integer, Integer, String, Integer, Integer, String, Integer, Integer, BigDecimal> {

    private static final long serialVersionUID = -58803851;

    /**
     * Setter for <code>inf.book.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>inf.book.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>inf.book.availableQty</code>.
     */
    public void setAvailableqty(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>inf.book.availableQty</code>.
     */
    public Integer getAvailableqty() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>inf.book.pendingQty</code>.
     */
    public void setPendingqty(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>inf.book.pendingQty</code>.
     */
    public Integer getPendingqty() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>inf.book.name</code>.
     */
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>inf.book.name</code>.
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>inf.book.medium</code>.
     */
    public void setMedium(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>inf.book.medium</code>.
     */
    public Integer getMedium() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>inf.book.grade</code>.
     */
    public void setGrade(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>inf.book.grade</code>.
     */
    public Integer getGrade() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>inf.book.authorName</code>.
     */
    public void setAuthorname(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>inf.book.authorName</code>.
     */
    public String getAuthorname() {
        return (String) get(6);
    }

    /**
     * Setter for <code>inf.book.noOfPages</code>.
     */
    public void setNoofpages(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>inf.book.noOfPages</code>.
     */
    public Integer getNoofpages() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>inf.book.status</code>.
     */
    public void setStatus(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>inf.book.status</code>.
     */
    public Integer getStatus() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>inf.book.price</code>.
     */
    public void setPrice(BigDecimal value) {
        set(9, value);
    }

    /**
     * Getter for <code>inf.book.price</code>.
     */
    public BigDecimal getPrice() {
        return (BigDecimal) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, Integer, Integer, String, Integer, Integer, String, Integer, Integer, BigDecimal> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, Integer, Integer, String, Integer, Integer, String, Integer, Integer, BigDecimal> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Book.BOOK.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Book.BOOK.AVAILABLEQTY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Book.BOOK.PENDINGQTY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Book.BOOK.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Book.BOOK.MEDIUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return Book.BOOK.GRADE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Book.BOOK.AUTHORNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return Book.BOOK.NOOFPAGES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return Book.BOOK.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field10() {
        return Book.BOOK.PRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getAvailableqty();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getPendingqty();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getMedium();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getGrade();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getAuthorname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getNoofpages();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value10() {
        return getPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookRecord value2(Integer value) {
        setAvailableqty(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookRecord value3(Integer value) {
        setPendingqty(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookRecord value4(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookRecord value5(Integer value) {
        setMedium(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookRecord value6(Integer value) {
        setGrade(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookRecord value7(String value) {
        setAuthorname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookRecord value8(Integer value) {
        setNoofpages(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookRecord value9(Integer value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookRecord value10(BigDecimal value) {
        setPrice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookRecord values(Integer value1, Integer value2, Integer value3, String value4, Integer value5, Integer value6, String value7, Integer value8, Integer value9, BigDecimal value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BookRecord
     */
    public BookRecord() {
        super(Book.BOOK);
    }

    /**
     * Create a detached, initialised BookRecord
     */
    public BookRecord(Integer id, Integer availableqty, Integer pendingqty, String name, Integer medium, Integer grade, String authorname, Integer noofpages, Integer status, BigDecimal price) {
        super(Book.BOOK);

        set(0, id);
        set(1, availableqty);
        set(2, pendingqty);
        set(3, name);
        set(4, medium);
        set(5, grade);
        set(6, authorname);
        set(7, noofpages);
        set(8, status);
        set(9, price);
    }
}
