/**
 * This class is generated by jOOQ
 */
package com.infsystem.infsystem.databse.jooq.model.tables.records;


import com.infsystem.infsystem.databse.jooq.model.tables.JobTask;

import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JobTaskRecord extends UpdatableRecordImpl<JobTaskRecord> implements Record12<Integer, Integer, Integer, Integer, Integer, Date, Integer, Date, Integer, Date, Date, Integer> {

    private static final long serialVersionUID = 624745625;

    /**
     * Setter for <code>inf.job_task.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>inf.job_task.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>inf.job_task.jobId</code>.
     */
    public void setJobid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>inf.job_task.jobId</code>.
     */
    public Integer getJobid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>inf.job_task.state</code>.
     */
    public void setState(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>inf.job_task.state</code>.
     */
    public Integer getState() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>inf.job_task.taskType</code>.
     */
    public void setTasktype(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>inf.job_task.taskType</code>.
     */
    public Integer getTasktype() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>inf.job_task.taskExicuteMethod</code>.
     */
    public void setTaskexicutemethod(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>inf.job_task.taskExicuteMethod</code>.
     */
    public Integer getTaskexicutemethod() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>inf.job_task.createDate</code>.
     */
    public void setCreatedate(Date value) {
        set(5, value);
    }

    /**
     * Getter for <code>inf.job_task.createDate</code>.
     */
    public Date getCreatedate() {
        return (Date) get(5);
    }

    /**
     * Setter for <code>inf.job_task.createBy</code>.
     */
    public void setCreateby(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>inf.job_task.createBy</code>.
     */
    public Integer getCreateby() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>inf.job_task.modifyDate</code>.
     */
    public void setModifydate(Date value) {
        set(7, value);
    }

    /**
     * Getter for <code>inf.job_task.modifyDate</code>.
     */
    public Date getModifydate() {
        return (Date) get(7);
    }

    /**
     * Setter for <code>inf.job_task.modifyBy</code>.
     */
    public void setModifyby(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>inf.job_task.modifyBy</code>.
     */
    public Integer getModifyby() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>inf.job_task.startDate</code>.
     */
    public void setStartdate(Date value) {
        set(9, value);
    }

    /**
     * Getter for <code>inf.job_task.startDate</code>.
     */
    public Date getStartdate() {
        return (Date) get(9);
    }

    /**
     * Setter for <code>inf.job_task.endDate</code>.
     */
    public void setEnddate(Date value) {
        set(10, value);
    }

    /**
     * Getter for <code>inf.job_task.endDate</code>.
     */
    public Date getEnddate() {
        return (Date) get(10);
    }

    /**
     * Setter for <code>inf.job_task.quantity</code>.
     */
    public void setQuantity(Integer value) {
        set(11, value);
    }

    /**
     * Getter for <code>inf.job_task.quantity</code>.
     */
    public Integer getQuantity() {
        return (Integer) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Integer, Integer, Integer, Integer, Integer, Date, Integer, Date, Integer, Date, Date, Integer> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Integer, Integer, Integer, Integer, Integer, Date, Integer, Date, Integer, Date, Date, Integer> valuesRow() {
        return (Row12) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return JobTask.JOB_TASK.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return JobTask.JOB_TASK.JOBID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return JobTask.JOB_TASK.STATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return JobTask.JOB_TASK.TASKTYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return JobTask.JOB_TASK.TASKEXICUTEMETHOD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field6() {
        return JobTask.JOB_TASK.CREATEDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return JobTask.JOB_TASK.CREATEBY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field8() {
        return JobTask.JOB_TASK.MODIFYDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return JobTask.JOB_TASK.MODIFYBY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field10() {
        return JobTask.JOB_TASK.STARTDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field11() {
        return JobTask.JOB_TASK.ENDDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field12() {
        return JobTask.JOB_TASK.QUANTITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getJobid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getTasktype();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getTaskexicutemethod();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value6() {
        return getCreatedate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getCreateby();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value8() {
        return getModifydate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getModifyby();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value10() {
        return getStartdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value11() {
        return getEnddate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value12() {
        return getQuantity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobTaskRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobTaskRecord value2(Integer value) {
        setJobid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobTaskRecord value3(Integer value) {
        setState(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobTaskRecord value4(Integer value) {
        setTasktype(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobTaskRecord value5(Integer value) {
        setTaskexicutemethod(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobTaskRecord value6(Date value) {
        setCreatedate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobTaskRecord value7(Integer value) {
        setCreateby(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobTaskRecord value8(Date value) {
        setModifydate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobTaskRecord value9(Integer value) {
        setModifyby(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobTaskRecord value10(Date value) {
        setStartdate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobTaskRecord value11(Date value) {
        setEnddate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobTaskRecord value12(Integer value) {
        setQuantity(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobTaskRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Integer value5, Date value6, Integer value7, Date value8, Integer value9, Date value10, Date value11, Integer value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JobTaskRecord
     */
    public JobTaskRecord() {
        super(JobTask.JOB_TASK);
    }

    /**
     * Create a detached, initialised JobTaskRecord
     */
    public JobTaskRecord(Integer id, Integer jobid, Integer state, Integer tasktype, Integer taskexicutemethod, Date createdate, Integer createby, Date modifydate, Integer modifyby, Date startdate, Date enddate, Integer quantity) {
        super(JobTask.JOB_TASK);

        set(0, id);
        set(1, jobid);
        set(2, state);
        set(3, tasktype);
        set(4, taskexicutemethod);
        set(5, createdate);
        set(6, createby);
        set(7, modifydate);
        set(8, modifyby);
        set(9, startdate);
        set(10, enddate);
        set(11, quantity);
    }
}
