/**
 * This class is generated by jOOQ
 */
package com.infsystem.infsystem.databse.jooq.model.tables.records;


import com.infsystem.infsystem.databse.jooq.model.tables.JobTaskVendor;

import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JobTaskVendorRecord extends UpdatableRecordImpl<JobTaskVendorRecord> implements Record6<Integer, Integer, Integer, Date, Date, Date> {

    private static final long serialVersionUID = -828369130;

    /**
     * Setter for <code>inf.job_task_vendor.taskId</code>.
     */
    public void setTaskid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>inf.job_task_vendor.taskId</code>.
     */
    public Integer getTaskid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>inf.job_task_vendor.vendorId</code>.
     */
    public void setVendorid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>inf.job_task_vendor.vendorId</code>.
     */
    public Integer getVendorid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>inf.job_task_vendor.quantityGiven</code>.
     */
    public void setQuantitygiven(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>inf.job_task_vendor.quantityGiven</code>.
     */
    public Integer getQuantitygiven() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>inf.job_task_vendor.initDate</code>.
     */
    public void setInitdate(Date value) {
        set(3, value);
    }

    /**
     * Getter for <code>inf.job_task_vendor.initDate</code>.
     */
    public Date getInitdate() {
        return (Date) get(3);
    }

    /**
     * Setter for <code>inf.job_task_vendor.finished</code>.
     */
    public void setFinished(Date value) {
        set(4, value);
    }

    /**
     * Getter for <code>inf.job_task_vendor.finished</code>.
     */
    public Date getFinished() {
        return (Date) get(4);
    }

    /**
     * Setter for <code>inf.job_task_vendor.expectedFinished</code>.
     */
    public void setExpectedfinished(Date value) {
        set(5, value);
    }

    /**
     * Getter for <code>inf.job_task_vendor.expectedFinished</code>.
     */
    public Date getExpectedfinished() {
        return (Date) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Integer, Integer, Date, Date, Date> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Integer, Integer, Date, Date, Date> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return JobTaskVendor.JOB_TASK_VENDOR.TASKID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return JobTaskVendor.JOB_TASK_VENDOR.VENDORID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return JobTaskVendor.JOB_TASK_VENDOR.QUANTITYGIVEN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field4() {
        return JobTaskVendor.JOB_TASK_VENDOR.INITDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field5() {
        return JobTaskVendor.JOB_TASK_VENDOR.FINISHED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field6() {
        return JobTaskVendor.JOB_TASK_VENDOR.EXPECTEDFINISHED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getTaskid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getVendorid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getQuantitygiven();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value4() {
        return getInitdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value5() {
        return getFinished();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value6() {
        return getExpectedfinished();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobTaskVendorRecord value1(Integer value) {
        setTaskid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobTaskVendorRecord value2(Integer value) {
        setVendorid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobTaskVendorRecord value3(Integer value) {
        setQuantitygiven(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobTaskVendorRecord value4(Date value) {
        setInitdate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobTaskVendorRecord value5(Date value) {
        setFinished(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobTaskVendorRecord value6(Date value) {
        setExpectedfinished(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobTaskVendorRecord values(Integer value1, Integer value2, Integer value3, Date value4, Date value5, Date value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JobTaskVendorRecord
     */
    public JobTaskVendorRecord() {
        super(JobTaskVendor.JOB_TASK_VENDOR);
    }

    /**
     * Create a detached, initialised JobTaskVendorRecord
     */
    public JobTaskVendorRecord(Integer taskid, Integer vendorid, Integer quantitygiven, Date initdate, Date finished, Date expectedfinished) {
        super(JobTaskVendor.JOB_TASK_VENDOR);

        set(0, taskid);
        set(1, vendorid);
        set(2, quantitygiven);
        set(3, initdate);
        set(4, finished);
        set(5, expectedfinished);
    }
}
