/**
 * This class is generated by jOOQ
 */
package com.infsystem.infsystem.databse.jooq.model.tables.records;


import com.infsystem.infsystem.databse.jooq.model.tables.Address;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AddressRecord extends UpdatableRecordImpl<AddressRecord> implements Record11<Integer, Integer, Integer, String, String, String, String, String, String, String, String> {

    private static final long serialVersionUID = 997092451;

    /**
     * Setter for <code>inf.address.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>inf.address.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>inf.address.userId</code>.
     */
    public void setUserid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>inf.address.userId</code>.
     */
    public Integer getUserid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>inf.address.type</code>.
     */
    public void setType(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>inf.address.type</code>.
     */
    public Integer getType() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>inf.address.addressNo</code>.
     */
    public void setAddressno(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>inf.address.addressNo</code>.
     */
    public String getAddressno() {
        return (String) get(3);
    }

    /**
     * Setter for <code>inf.address.addressStreet1</code>.
     */
    public void setAddressstreet1(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>inf.address.addressStreet1</code>.
     */
    public String getAddressstreet1() {
        return (String) get(4);
    }

    /**
     * Setter for <code>inf.address.addressStreet2</code>.
     */
    public void setAddressstreet2(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>inf.address.addressStreet2</code>.
     */
    public String getAddressstreet2() {
        return (String) get(5);
    }

    /**
     * Setter for <code>inf.address.addressStreet3</code>.
     */
    public void setAddressstreet3(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>inf.address.addressStreet3</code>.
     */
    public String getAddressstreet3() {
        return (String) get(6);
    }

    /**
     * Setter for <code>inf.address.addressCity</code>.
     */
    public void setAddresscity(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>inf.address.addressCity</code>.
     */
    public String getAddresscity() {
        return (String) get(7);
    }

    /**
     * Setter for <code>inf.address.addressCountry</code>.
     */
    public void setAddresscountry(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>inf.address.addressCountry</code>.
     */
    public String getAddresscountry() {
        return (String) get(8);
    }

    /**
     * Setter for <code>inf.address.contactPreson</code>.
     */
    public void setContactpreson(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>inf.address.contactPreson</code>.
     */
    public String getContactpreson() {
        return (String) get(9);
    }

    /**
     * Setter for <code>inf.address.telephoneNumber</code>.
     */
    public void setTelephonenumber(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>inf.address.telephoneNumber</code>.
     */
    public String getTelephonenumber() {
        return (String) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Integer, Integer, Integer, String, String, String, String, String, String, String, String> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<Integer, Integer, Integer, String, String, String, String, String, String, String, String> valuesRow() {
        return (Row11) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Address.ADDRESS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Address.ADDRESS.USERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Address.ADDRESS.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Address.ADDRESS.ADDRESSNO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Address.ADDRESS.ADDRESSSTREET1;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Address.ADDRESS.ADDRESSSTREET2;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Address.ADDRESS.ADDRESSSTREET3;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Address.ADDRESS.ADDRESSCITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Address.ADDRESS.ADDRESSCOUNTRY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return Address.ADDRESS.CONTACTPRESON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return Address.ADDRESS.TELEPHONENUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getUserid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getAddressno();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getAddressstreet1();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getAddressstreet2();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getAddressstreet3();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getAddresscity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getAddresscountry();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getContactpreson();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getTelephonenumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AddressRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AddressRecord value2(Integer value) {
        setUserid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AddressRecord value3(Integer value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AddressRecord value4(String value) {
        setAddressno(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AddressRecord value5(String value) {
        setAddressstreet1(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AddressRecord value6(String value) {
        setAddressstreet2(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AddressRecord value7(String value) {
        setAddressstreet3(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AddressRecord value8(String value) {
        setAddresscity(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AddressRecord value9(String value) {
        setAddresscountry(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AddressRecord value10(String value) {
        setContactpreson(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AddressRecord value11(String value) {
        setTelephonenumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AddressRecord values(Integer value1, Integer value2, Integer value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, String value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AddressRecord
     */
    public AddressRecord() {
        super(Address.ADDRESS);
    }

    /**
     * Create a detached, initialised AddressRecord
     */
    public AddressRecord(Integer id, Integer userid, Integer type, String addressno, String addressstreet1, String addressstreet2, String addressstreet3, String addresscity, String addresscountry, String contactpreson, String telephonenumber) {
        super(Address.ADDRESS);

        set(0, id);
        set(1, userid);
        set(2, type);
        set(3, addressno);
        set(4, addressstreet1);
        set(5, addressstreet2);
        set(6, addressstreet3);
        set(7, addresscity);
        set(8, addresscountry);
        set(9, contactpreson);
        set(10, telephonenumber);
    }
}
