/**
 * This class is generated by jOOQ
 */
package com.infsystem.infsystem.databse.jooq.model.tables.records;


import com.infsystem.infsystem.databse.jooq.model.tables.BookMedium;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BookMediumRecord extends UpdatableRecordImpl<BookMediumRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = -1626239855;

    /**
     * Setter for <code>inf.book_medium.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>inf.book_medium.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>inf.book_medium.medium</code>.
     */
    public void setMedium(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>inf.book_medium.medium</code>.
     */
    public String getMedium() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return BookMedium.BOOK_MEDIUM.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return BookMedium.BOOK_MEDIUM.MEDIUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getMedium();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookMediumRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookMediumRecord value2(String value) {
        setMedium(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookMediumRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BookMediumRecord
     */
    public BookMediumRecord() {
        super(BookMedium.BOOK_MEDIUM);
    }

    /**
     * Create a detached, initialised BookMediumRecord
     */
    public BookMediumRecord(Integer id, String medium) {
        super(BookMedium.BOOK_MEDIUM);

        set(0, id);
        set(1, medium);
    }
}
