/**
 * This class is generated by jOOQ
 */
package com.infsystem.infsystem.databse.jooq.model.tables.records;


import com.infsystem.infsystem.databse.jooq.model.tables.MaterialSuplier;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MaterialSuplierRecord extends UpdatableRecordImpl<MaterialSuplierRecord> implements Record3<Integer, Integer, Integer> {

    private static final long serialVersionUID = 461943049;

    /**
     * Setter for <code>inf.material_suplier.suplierId</code>.
     */
    public void setSuplierid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>inf.material_suplier.suplierId</code>.
     */
    public Integer getSuplierid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>inf.material_suplier.materialId</code>.
     */
    public void setMaterialid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>inf.material_suplier.materialId</code>.
     */
    public Integer getMaterialid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>inf.material_suplier.price</code>.
     */
    public void setPrice(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>inf.material_suplier.price</code>.
     */
    public Integer getPrice() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return MaterialSuplier.MATERIAL_SUPLIER.SUPLIERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return MaterialSuplier.MATERIAL_SUPLIER.MATERIALID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return MaterialSuplier.MATERIAL_SUPLIER.PRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getSuplierid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getMaterialid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MaterialSuplierRecord value1(Integer value) {
        setSuplierid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MaterialSuplierRecord value2(Integer value) {
        setMaterialid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MaterialSuplierRecord value3(Integer value) {
        setPrice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MaterialSuplierRecord values(Integer value1, Integer value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MaterialSuplierRecord
     */
    public MaterialSuplierRecord() {
        super(MaterialSuplier.MATERIAL_SUPLIER);
    }

    /**
     * Create a detached, initialised MaterialSuplierRecord
     */
    public MaterialSuplierRecord(Integer suplierid, Integer materialid, Integer price) {
        super(MaterialSuplier.MATERIAL_SUPLIER);

        set(0, suplierid);
        set(1, materialid);
        set(2, price);
    }
}
