/**
 * This class is generated by jOOQ
 */
package com.infsystem.infsystem.databse.jooq.model.tables.records;


import com.infsystem.infsystem.databse.jooq.model.tables.Material;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MaterialRecord extends UpdatableRecordImpl<MaterialRecord> implements Record8<Integer, String, Integer, Integer, Integer, String, String, Integer> {

    private static final long serialVersionUID = -2016293226;

    /**
     * Setter for <code>inf.material.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>inf.material.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>inf.material.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>inf.material.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>inf.material.categoryId</code>.
     */
    public void setCategoryid(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>inf.material.categoryId</code>.
     */
    public Integer getCategoryid() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>inf.material.availableQty</code>.
     */
    public void setAvailableqty(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>inf.material.availableQty</code>.
     */
    public Integer getAvailableqty() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>inf.material.pendingQty</code>.
     */
    public void setPendingqty(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>inf.material.pendingQty</code>.
     */
    public Integer getPendingqty() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>inf.material.brand</code>.
     */
    public void setBrand(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>inf.material.brand</code>.
     */
    public String getBrand() {
        return (String) get(5);
    }

    /**
     * Setter for <code>inf.material.description</code>.
     */
    public void setDescription(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>inf.material.description</code>.
     */
    public String getDescription() {
        return (String) get(6);
    }

    /**
     * Setter for <code>inf.material.trigerLimit</code>.
     */
    public void setTrigerlimit(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>inf.material.trigerLimit</code>.
     */
    public Integer getTrigerlimit() {
        return (Integer) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, Integer, Integer, Integer, String, String, Integer> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, Integer, Integer, Integer, String, String, Integer> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Material.MATERIAL.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Material.MATERIAL.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Material.MATERIAL.CATEGORYID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Material.MATERIAL.AVAILABLEQTY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Material.MATERIAL.PENDINGQTY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Material.MATERIAL.BRAND;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Material.MATERIAL.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return Material.MATERIAL.TRIGERLIMIT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getCategoryid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getAvailableqty();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getPendingqty();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getBrand();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getTrigerlimit();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MaterialRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MaterialRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MaterialRecord value3(Integer value) {
        setCategoryid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MaterialRecord value4(Integer value) {
        setAvailableqty(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MaterialRecord value5(Integer value) {
        setPendingqty(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MaterialRecord value6(String value) {
        setBrand(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MaterialRecord value7(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MaterialRecord value8(Integer value) {
        setTrigerlimit(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MaterialRecord values(Integer value1, String value2, Integer value3, Integer value4, Integer value5, String value6, String value7, Integer value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MaterialRecord
     */
    public MaterialRecord() {
        super(Material.MATERIAL);
    }

    /**
     * Create a detached, initialised MaterialRecord
     */
    public MaterialRecord(Integer id, String name, Integer categoryid, Integer availableqty, Integer pendingqty, String brand, String description, Integer trigerlimit) {
        super(Material.MATERIAL);

        set(0, id);
        set(1, name);
        set(2, categoryid);
        set(3, availableqty);
        set(4, pendingqty);
        set(5, brand);
        set(6, description);
        set(7, trigerlimit);
    }
}
