/**
 * This class is generated by jOOQ
 */
package com.infsystem.infsystem.databse.jooq.model.tables.records;


import com.infsystem.infsystem.databse.jooq.model.tables.Orders;

import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrdersRecord extends UpdatableRecordImpl<OrdersRecord> implements Record7<Integer, Date, Integer, Date, Integer, Integer, Integer> {

    private static final long serialVersionUID = -512706654;

    /**
     * Setter for <code>inf.orders.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>inf.orders.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>inf.orders.createDate</code>.
     */
    public void setCreatedate(Date value) {
        set(1, value);
    }

    /**
     * Getter for <code>inf.orders.createDate</code>.
     */
    public Date getCreatedate() {
        return (Date) get(1);
    }

    /**
     * Setter for <code>inf.orders.createBy</code>.
     */
    public void setCreateby(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>inf.orders.createBy</code>.
     */
    public Integer getCreateby() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>inf.orders.modifyDate</code>.
     */
    public void setModifydate(Date value) {
        set(3, value);
    }

    /**
     * Getter for <code>inf.orders.modifyDate</code>.
     */
    public Date getModifydate() {
        return (Date) get(3);
    }

    /**
     * Setter for <code>inf.orders.modifyBy</code>.
     */
    public void setModifyby(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>inf.orders.modifyBy</code>.
     */
    public Integer getModifyby() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>inf.orders.client</code>.
     */
    public void setClient(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>inf.orders.client</code>.
     */
    public Integer getClient() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>inf.orders.state</code>.
     */
    public void setState(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>inf.orders.state</code>.
     */
    public Integer getState() {
        return (Integer) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Date, Integer, Date, Integer, Integer, Integer> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Date, Integer, Date, Integer, Integer, Integer> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Orders.ORDERS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field2() {
        return Orders.ORDERS.CREATEDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Orders.ORDERS.CREATEBY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field4() {
        return Orders.ORDERS.MODIFYDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Orders.ORDERS.MODIFYBY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return Orders.ORDERS.CLIENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return Orders.ORDERS.STATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value2() {
        return getCreatedate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getCreateby();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value4() {
        return getModifydate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getModifyby();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getClient();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrdersRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrdersRecord value2(Date value) {
        setCreatedate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrdersRecord value3(Integer value) {
        setCreateby(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrdersRecord value4(Date value) {
        setModifydate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrdersRecord value5(Integer value) {
        setModifyby(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrdersRecord value6(Integer value) {
        setClient(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrdersRecord value7(Integer value) {
        setState(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrdersRecord values(Integer value1, Date value2, Integer value3, Date value4, Integer value5, Integer value6, Integer value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrdersRecord
     */
    public OrdersRecord() {
        super(Orders.ORDERS);
    }

    /**
     * Create a detached, initialised OrdersRecord
     */
    public OrdersRecord(Integer id, Date createdate, Integer createby, Date modifydate, Integer modifyby, Integer client, Integer state) {
        super(Orders.ORDERS);

        set(0, id);
        set(1, createdate);
        set(2, createby);
        set(3, modifydate);
        set(4, modifyby);
        set(5, client);
        set(6, state);
    }
}
