/**
 * This class is generated by jOOQ
 */
package com.infsystem.infsystem.databse.jooq.model.tables;


import com.infsystem.infsystem.databse.jooq.model.Inf;
import com.infsystem.infsystem.databse.jooq.model.Keys;
import com.infsystem.infsystem.databse.jooq.model.tables.records.AddresstypeRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Addresstype extends TableImpl<AddresstypeRecord> {

    private static final long serialVersionUID = -1354439783;

    /**
     * The reference instance of <code>inf.addresstype</code>
     */
    public static final Addresstype ADDRESSTYPE = new Addresstype();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AddresstypeRecord> getRecordType() {
        return AddresstypeRecord.class;
    }

    /**
     * The column <code>inf.addresstype.id</code>.
     */
    public final TableField<AddresstypeRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>inf.addresstype.name</code>.
     */
    public final TableField<AddresstypeRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(30), this, "");

    /**
     * Create a <code>inf.addresstype</code> table reference
     */
    public Addresstype() {
        this("addresstype", null);
    }

    /**
     * Create an aliased <code>inf.addresstype</code> table reference
     */
    public Addresstype(String alias) {
        this(alias, ADDRESSTYPE);
    }

    private Addresstype(String alias, Table<AddresstypeRecord> aliased) {
        this(alias, aliased, null);
    }

    private Addresstype(String alias, Table<AddresstypeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Inf.INF;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<AddresstypeRecord, Integer> getIdentity() {
        return Keys.IDENTITY_ADDRESSTYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<AddresstypeRecord> getPrimaryKey() {
        return Keys.KEY_ADDRESSTYPE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<AddresstypeRecord>> getKeys() {
        return Arrays.<UniqueKey<AddresstypeRecord>>asList(Keys.KEY_ADDRESSTYPE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Addresstype as(String alias) {
        return new Addresstype(alias, this);
    }

    /**
     * Rename this table
     */
    public Addresstype rename(String name) {
        return new Addresstype(name, null);
    }
}
