/**
 * This class is generated by jOOQ
 */
package com.infsystem.infsystem.databse.jooq.model.tables;


import com.infsystem.infsystem.databse.jooq.model.Inf;
import com.infsystem.infsystem.databse.jooq.model.Keys;
import com.infsystem.infsystem.databse.jooq.model.tables.records.ChapterRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Chapter extends TableImpl<ChapterRecord> {

    private static final long serialVersionUID = 2124038395;

    /**
     * The reference instance of <code>inf.chapter</code>
     */
    public static final Chapter CHAPTER = new Chapter();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ChapterRecord> getRecordType() {
        return ChapterRecord.class;
    }

    /**
     * The column <code>inf.chapter.id</code>.
     */
    public final TableField<ChapterRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>inf.chapter.name</code>.
     */
    public final TableField<ChapterRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(120), this, "");

    /**
     * The column <code>inf.chapter.noOfPages</code>.
     */
    public final TableField<ChapterRecord, Integer> NOOFPAGES = createField("noOfPages", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>inf.chapter.bookId</code>.
     */
    public final TableField<ChapterRecord, Integer> BOOKID = createField("bookId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>inf.chapter.availableQty</code>.
     */
    public final TableField<ChapterRecord, Integer> AVAILABLEQTY = createField("availableQty", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>inf.chapter</code> table reference
     */
    public Chapter() {
        this("chapter", null);
    }

    /**
     * Create an aliased <code>inf.chapter</code> table reference
     */
    public Chapter(String alias) {
        this(alias, CHAPTER);
    }

    private Chapter(String alias, Table<ChapterRecord> aliased) {
        this(alias, aliased, null);
    }

    private Chapter(String alias, Table<ChapterRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Inf.INF;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ChapterRecord, Integer> getIdentity() {
        return Keys.IDENTITY_CHAPTER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ChapterRecord> getPrimaryKey() {
        return Keys.KEY_CHAPTER_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ChapterRecord>> getKeys() {
        return Arrays.<UniqueKey<ChapterRecord>>asList(Keys.KEY_CHAPTER_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<ChapterRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ChapterRecord, ?>>asList(Keys.FK_CHAPTER_BOOK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Chapter as(String alias) {
        return new Chapter(alias, this);
    }

    /**
     * Rename this table
     */
    public Chapter rename(String name) {
        return new Chapter(name, null);
    }
}
