/**
 * This class is generated by jOOQ
 */
package com.infsystem.infsystem.databse.jooq.model.tables;


import com.infsystem.infsystem.databse.jooq.model.Inf;
import com.infsystem.infsystem.databse.jooq.model.Keys;
import com.infsystem.infsystem.databse.jooq.model.tables.records.MaterialSuplierRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MaterialSuplier extends TableImpl<MaterialSuplierRecord> {

    private static final long serialVersionUID = 939755564;

    /**
     * The reference instance of <code>inf.material_suplier</code>
     */
    public static final MaterialSuplier MATERIAL_SUPLIER = new MaterialSuplier();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MaterialSuplierRecord> getRecordType() {
        return MaterialSuplierRecord.class;
    }

    /**
     * The column <code>inf.material_suplier.suplierId</code>.
     */
    public final TableField<MaterialSuplierRecord, Integer> SUPLIERID = createField("suplierId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>inf.material_suplier.materialId</code>.
     */
    public final TableField<MaterialSuplierRecord, Integer> MATERIALID = createField("materialId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>inf.material_suplier.price</code>.
     */
    public final TableField<MaterialSuplierRecord, Integer> PRICE = createField("price", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>inf.material_suplier</code> table reference
     */
    public MaterialSuplier() {
        this("material_suplier", null);
    }

    /**
     * Create an aliased <code>inf.material_suplier</code> table reference
     */
    public MaterialSuplier(String alias) {
        this(alias, MATERIAL_SUPLIER);
    }

    private MaterialSuplier(String alias, Table<MaterialSuplierRecord> aliased) {
        this(alias, aliased, null);
    }

    private MaterialSuplier(String alias, Table<MaterialSuplierRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Inf.INF;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<MaterialSuplierRecord> getPrimaryKey() {
        return Keys.KEY_MATERIAL_SUPLIER_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<MaterialSuplierRecord>> getKeys() {
        return Arrays.<UniqueKey<MaterialSuplierRecord>>asList(Keys.KEY_MATERIAL_SUPLIER_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<MaterialSuplierRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<MaterialSuplierRecord, ?>>asList(Keys.PK_MATERIALSUPLIER_PERSON, Keys.PK_MATERIALSUPLIER_MATERIAL);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MaterialSuplier as(String alias) {
        return new MaterialSuplier(alias, this);
    }

    /**
     * Rename this table
     */
    public MaterialSuplier rename(String name) {
        return new MaterialSuplier(name, null);
    }
}
