/**
 * This class is generated by jOOQ
 */
package com.infsystem.infsystem.databse.jooq.model.tables;


import com.infsystem.infsystem.databse.jooq.model.Inf;
import com.infsystem.infsystem.databse.jooq.model.Keys;
import com.infsystem.infsystem.databse.jooq.model.tables.records.PersontypeRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Persontype extends TableImpl<PersontypeRecord> {

    private static final long serialVersionUID = -1098996375;

    /**
     * The reference instance of <code>inf.persontype</code>
     */
    public static final Persontype PERSONTYPE = new Persontype();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PersontypeRecord> getRecordType() {
        return PersontypeRecord.class;
    }

    /**
     * The column <code>inf.persontype.id</code>.
     */
    public final TableField<PersontypeRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>inf.persontype.name</code>.
     */
    public final TableField<PersontypeRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(30), this, "");

    /**
     * Create a <code>inf.persontype</code> table reference
     */
    public Persontype() {
        this("persontype", null);
    }

    /**
     * Create an aliased <code>inf.persontype</code> table reference
     */
    public Persontype(String alias) {
        this(alias, PERSONTYPE);
    }

    private Persontype(String alias, Table<PersontypeRecord> aliased) {
        this(alias, aliased, null);
    }

    private Persontype(String alias, Table<PersontypeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Inf.INF;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<PersontypeRecord, Integer> getIdentity() {
        return Keys.IDENTITY_PERSONTYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<PersontypeRecord> getPrimaryKey() {
        return Keys.KEY_PERSONTYPE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<PersontypeRecord>> getKeys() {
        return Arrays.<UniqueKey<PersontypeRecord>>asList(Keys.KEY_PERSONTYPE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Persontype as(String alias) {
        return new Persontype(alias, this);
    }

    /**
     * Rename this table
     */
    public Persontype rename(String name) {
        return new Persontype(name, null);
    }
}
